#Travis CI Configuration File

# Required to run your project under the correct enviroment
language: php

# Versions of PHP you want your project to run with
php:
  - 7.2

# Installations
install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest
  - composer install

# Commands you want to run that will verify your build
script: 
# Test and generate Code Coverage report
  - phpunit --testdox --coverage-html coverage --whitelist src --bootstrap vendor/autoload.php tests
  - vendor/bin/phpunit --coverage-clover=coverage.xml

# after_script:

after_success:
# Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

# allow_failures: Allow this build to fail under the specified environments
# fast_finished: If your build fails, then do not continue tryong and just stop
matrix:
  allow_failures:
    - php: 7.2
  fast_finished: true 
